from devices import motor

def testMotor():
    print("=== Constructor Function ===")
    a = motor(port = motor.M1,ticks=100,acc=10,kp=5,ki=15)
    b = motor(port = motor.M1)
    print("\n=== Config Function ===")
    #a.config(direction = motor.REVERSE)
    print("\n=== Set Function ===")
    a.set(mode = motor.POWER_MODE, speed = 245)
    print("\n=== Config After Function ===")
    #a.config(direction = motor.REVERSE)
    print("\n=== Get Function ===")
    print(a.get())
    print(f"speed: {a.get()['speed']}" )
    print(f"power: {a.get()['power']}" )
    print(f"position: {a.get()['position']}" )
    print("\n=== Motor Status ===")
    print(f"Motor M1:       {motor.M1}")
    print(f"Motor M2:       {motor.M2}")
    print(f"Motor M3:       {motor.M3}")
    print(f"Motor M4:       {motor.M4}")
    print("---------------------")
   # print(f"Direction:      {'FORWARD' if motor.FORWARD else 'REVERSE'}")
   # print(f"motor.FORWARD:  {motor.FORWARD}")
   # print(f"motor.REVERSE:  {motor.REVERSE}")
    print(f"Power Mode:     {motor.POWER_MODE}")
    print(f"Brake Mode:     {motor.BRAKE_MODE}")
    print(f"Speed Mode:     {motor.SPEED_MODE}")
    print(f"Move To Mode:   {motor.MOVETO_MODE}")
    print("=====================")

testMotor()